# Generated by Django 4.0 on 2022-03-25 06:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='', max_length=50, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='job',
            name='full_part_time',
            field=models.BooleanField(default=False, verbose_name='Занятость'),
        ),
        migrations.AddField(
            model_name='job',
            name='number_of_ratings',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.IntegerField(default=0, verbose_name='Зарплата'),
        ),
        migrations.AddField(
            model_name='job',
            name='score',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='specialty',
            field=models.CharField(default='', max_length=50, verbose_name='Специализация'),
        ),
        migrations.AddField(
            model_name='job',
            name='work_graph',
            field=models.CharField(default='', max_length=20, verbose_name='График работы'),
        ),
    ]
