# Generated by Django 4.0 on 2022-03-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
