# Generated by Django 4.0 on 2022-04-03 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('news', '0004_delete_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liked_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='news.article')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_user', to='auth.user')),
            ],
        ),
    ]
