# Generated by Django 4.0 on 2022-04-10 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('job', '0004_job_image'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liked_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='job.job')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_user_job', to='auth.user')),
            ],
        ),
    ]
